// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrtSurvey.Context;

#nullable disable

namespace OrtSurvey.Migrations
{
    [DbContext(typeof(OrtSurveyDataBase))]
    [Migration("20260525201929_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrtSurvey.Models.Encuesta", b =>
                {
                    b.Property<int>("id_encuesta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_encuesta"));

                    b.Property<int?>("Usuarioid_usuario")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("es_publica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("fecha_cierre")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("fecha_creacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("id_encuesta");

                    b.HasIndex("Usuarioid_usuario");

                    b.HasIndex("id_usuario");

                    b.ToTable("Encuesta");
                });

            modelBuilder.Entity("OrtSurvey.Models.Opcion", b =>
                {
                    b.Property<int>("id_opcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_opcion"));

                    b.Property<int?>("Preguntaid_pregunta")
                        .HasColumnType("int");

                    b.Property<int>("id_pregunta")
                        .HasColumnType("int");

                    b.Property<string>("texto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("id_opcion");

                    b.HasIndex("Preguntaid_pregunta");

                    b.HasIndex("id_pregunta");

                    b.ToTable("Opciones");
                });

            modelBuilder.Entity("OrtSurvey.Models.Pregunta", b =>
                {
                    b.Property<int>("id_pregunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_pregunta"));

                    b.Property<int?>("Encuestaid_encuesta")
                        .HasColumnType("int");

                    b.Property<bool>("es_obligatoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("id_encuesta")
                        .HasColumnType("int");

                    b.Property<string>("texto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("tipo_pregunta")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("id_pregunta");

                    b.HasIndex("Encuestaid_encuesta");

                    b.HasIndex("id_encuesta");

                    b.ToTable("Preguntas");
                });

            modelBuilder.Entity("OrtSurvey.Models.Reporte", b =>
                {
                    b.Property<int>("id_reporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_reporte"));

                    b.Property<string>("correo_destino")
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime>("fecha_generacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("id_encuesta")
                        .HasColumnType("int");

                    b.Property<string>("tipo_reporte")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("id_reporte");

                    b.HasIndex("id_encuesta");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("OrtSurvey.Models.Respuesta", b =>
                {
                    b.Property<int>("id_respuesta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_respuesta"));

                    b.Property<int?>("Preguntaid_pregunta")
                        .HasColumnType("int");

                    b.Property<int?>("RespuestaEncuestaid_respuesta_encuesta")
                        .HasColumnType("int");

                    b.Property<int?>("id_opcion")
                        .HasColumnType("int");

                    b.Property<int>("id_pregunta")
                        .HasColumnType("int");

                    b.Property<int>("id_respuesta_encuesta")
                        .HasColumnType("int");

                    b.Property<string>("valor_texto")
                        .HasColumnType("varchar(500)");

                    b.HasKey("id_respuesta");

                    b.HasIndex("Preguntaid_pregunta");

                    b.HasIndex("RespuestaEncuestaid_respuesta_encuesta");

                    b.HasIndex("id_opcion");

                    b.HasIndex("id_pregunta");

                    b.HasIndex("id_respuesta_encuesta");

                    b.ToTable("Respuestas");
                });

            modelBuilder.Entity("OrtSurvey.Models.RespuestaEncuesta", b =>
                {
                    b.Property<int>("id_respuesta_encuesta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_respuesta_encuesta"));

                    b.Property<DateTime>("fecha_respuesta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("id_encuesta")
                        .HasColumnType("int");

                    b.Property<int?>("id_usuario")
                        .HasColumnType("int");

                    b.Property<string>("ip_respondedor")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("id_respuesta_encuesta");

                    b.HasIndex("id_encuesta");

                    b.HasIndex("id_usuario");

                    b.ToTable("RespuestasEncuestas");
                });

            modelBuilder.Entity("OrtSurvey.Models.Usuario", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_usuario"));

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime>("fecha_creacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("genero")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("id_usuario");

                    b.HasIndex("correo")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("OrtSurvey.Models.Encuesta", b =>
                {
                    b.HasOne("OrtSurvey.Models.Usuario", null)
                        .WithMany("Encuestas")
                        .HasForeignKey("Usuarioid_usuario");

                    b.HasOne("OrtSurvey.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OrtSurvey.Models.Opcion", b =>
                {
                    b.HasOne("OrtSurvey.Models.Pregunta", null)
                        .WithMany("Opciones")
                        .HasForeignKey("Preguntaid_pregunta");

                    b.HasOne("OrtSurvey.Models.Pregunta", "Pregunta")
                        .WithMany()
                        .HasForeignKey("id_pregunta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("OrtSurvey.Models.Pregunta", b =>
                {
                    b.HasOne("OrtSurvey.Models.Encuesta", null)
                        .WithMany("Preguntas")
                        .HasForeignKey("Encuestaid_encuesta");

                    b.HasOne("OrtSurvey.Models.Encuesta", "Encuesta")
                        .WithMany()
                        .HasForeignKey("id_encuesta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encuesta");
                });

            modelBuilder.Entity("OrtSurvey.Models.Reporte", b =>
                {
                    b.HasOne("OrtSurvey.Models.Encuesta", "Encuesta")
                        .WithMany()
                        .HasForeignKey("id_encuesta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encuesta");
                });

            modelBuilder.Entity("OrtSurvey.Models.Respuesta", b =>
                {
                    b.HasOne("OrtSurvey.Models.Pregunta", null)
                        .WithMany("Respuestas")
                        .HasForeignKey("Preguntaid_pregunta");

                    b.HasOne("OrtSurvey.Models.RespuestaEncuesta", null)
                        .WithMany("Respuestas")
                        .HasForeignKey("RespuestaEncuestaid_respuesta_encuesta");

                    b.HasOne("OrtSurvey.Models.Opcion", "Opcion")
                        .WithMany()
                        .HasForeignKey("id_opcion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OrtSurvey.Models.Pregunta", "Pregunta")
                        .WithMany()
                        .HasForeignKey("id_pregunta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrtSurvey.Models.RespuestaEncuesta", "RespuestaEncuesta")
                        .WithMany()
                        .HasForeignKey("id_respuesta_encuesta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opcion");

                    b.Navigation("Pregunta");

                    b.Navigation("RespuestaEncuesta");
                });

            modelBuilder.Entity("OrtSurvey.Models.RespuestaEncuesta", b =>
                {
                    b.HasOne("OrtSurvey.Models.Encuesta", "Encuesta")
                        .WithMany()
                        .HasForeignKey("id_encuesta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrtSurvey.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Encuesta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OrtSurvey.Models.Encuesta", b =>
                {
                    b.Navigation("Preguntas");
                });

            modelBuilder.Entity("OrtSurvey.Models.Pregunta", b =>
                {
                    b.Navigation("Opciones");

                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("OrtSurvey.Models.RespuestaEncuesta", b =>
                {
                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("OrtSurvey.Models.Usuario", b =>
                {
                    b.Navigation("Encuestas");
                });
#pragma warning restore 612, 618
        }
    }
}
